### ISSUE TITLE
Error running the tests

### ISSUE THREAD

**Issue by huogerac** [vintasoftware/django-role-permissions#40]
Hi,

When I was running the tests: `python setup.py test`

I got the following error, am I doing something wrong?

```
.../django-role-permissions/.eggs/Sphinx-1.4.1-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 90, in <module>
    tests_require=test_requirements
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File ".../workspacepy/dj19/local/lib/python2.7/site-packages/setuptools/command/test.py", line 152, in run
    self.distribution.fetch_build_eggs(self.distribution.tests_require)
  File ".../workspacepy/dj19/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File ".../workspacepy/dj19/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 825, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File ".../workspacepy/dj19/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1063, in best_match
    dist = working_set.find(req)
  File ".../workspacepy/dj19/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 700, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (six 1.9.0 (.../workspacepy/dj19/lib/python2.7/site-packages), Requirement.parse('six==1.3.0'))
```

Cheers

**Comment by filipeximenes** [comment]
Hey, sorry for this. The README was giving the wrong instructions, just updated it. 
Please run tests with `tox`.
