### ISSUE TITLE
Using package with Factory Boy

### ISSUE THREAD

**Issue by msamoylov** [vintasoftware/django-role-permissions#54]
Hi. I'm having issues with creating a factory for my roles. Any ideas how to fix that? Thanks!

**roles.py**

```
from rolepermissions.roles import AbstractUserRole

from applications.models import Application


class Evaluator(AbstractUserRole):
    available_permissions = dict(map(lambda x: (x[0], True), Application._meta.permissions))
```

**factories.py**

```
import factory

from django.conf import settings

from rolepermissions.shortcuts import assign_role

from project.roles import Operator
from universities.factories import UniversityFactory


class EvaluatorFactory(factory.django.DjangoModelFactory):
    email = factory.Sequence(lambda n: 'evaluator%d@example.com' % n)
    password = factory.PostGenerationMethodCall('set_password', settings.TEST_LOGIN_PASSWORD)
    first_name = factory.Faker('first_name')
    last_name = factory.Faker('last_name')
    university = factory.SubFactory(UniversityFactory)

    role = factory.PostGeneration(lambda obj, create, extracted, **kwargs: assign_role(obj, Evaluator))

    class Meta:
        model = 'users.User'
        django_get_or_create = ('email',)
```

My test are throwing errors like:

```
======================================================================
ERROR: test_access_denied_anonymous (users.tests.test_views.UserToggleStatusTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mike/Projects/project/users/tests/test_views.py", line 118, in setUp
    self.evaluator = EvaluatorFactory()
  File "/Users/mike/.pyenv/versions/project/lib/python3.5/site-packages/factory/base.py", line 67, in __call__
    return cls.create(**kwargs)
  File "/Users/mike/.pyenv/versions/project/lib/python3.5/site-packages/factory/base.py", line 594, in create
    return cls._generate(True, attrs)
  File "/Users/mike/.pyenv/versions/project/lib/python3.5/site-packages/factory/base.py", line 525, in _generate
    results[name] = decl.call(obj, create, extraction_context)
  File "/Users/mike/.pyenv/versions/project/lib/python3.5/site-packages/factory/declarations.py", line 562, in call
    extraction_context.value, **extraction_context.extra)
  File "/Users/mike/Projects/project/users/factories.py", line 52, in <lambda>
    role = factory.PostGeneration(lambda obj, create, extracted, **kwargs: assign_role(obj, Evaluator))
  File "/Users/mike/.pyenv/versions/project/lib/python3.5/site-packages/rolepermissions/shortcuts.py", line 31, in assign_role
    raise RoleDoesNotExist
rolepermissions.exceptions.RoleDoesNotExist
```

**Comment by msamoylov** [comment]
I shouldn't be accessing roles directly with a class name. `role = factory.PostGeneration(lambda obj, create, extracted, **kwargs: assign_role(obj, 'evaluator'))` does the trick.

Sorry for the false alert and thank you for your great package.
